class Login_Locators:
    User_Name_Field = "//input[@name='username']"
    Password_Field = "//input[@type='password']"
    Login_Button = "//ion-button[contains(.,'Login')]"


class Patients_Locators:
    Patient_Tab = "//ion-tab-button[contains(.,'Patients')]"
    Patient_Reg_Icon = "//ion-button[contains(@slot,'only-icon')]"
    New_Patient_Button = "//ion-text[@color='gray80'][contains(.,'New Patient')]"
    
    PCP_Group = "(//span[@ng-reflect-ng-class='k-i-caret-alt-down'])[10]"
    PGP_Group = "(//span[@ng-reflect-ng-class='k-i-caret-alt-down'])[12]"

    Value_Program_BOX = "//input[@placeholder='*Value Program']"
    PCP_Provider = "//input[@placeholder='Primary Care Provider']"
    Provider = "//input[@placeholder='Provider']" 

    FIRST_NAME_BOX = "//input[@placeholder='*First Name']"
    MIDDLE_NAME_BOX = "//input[@placeholder='Middle Name']"
    LAST_NAME_BOX = "//input[contains(@placeholder,'*Last Name')]"
    BIRTHDATE_FIELD = "//input[@id='datepicker-3']"
    GENDER_BOX = "//input[@placeholder='*Gender']"
    ADDRESS_FIELD = "//input[contains(@placeholder,'Address 1')]"
    ZIP_CODE_BOX = "//input[@placeholder='Zip']"
    MOBILE_NUMBER_FIELD = "(//input[contains(@type,'text')])[1]"
    HOME_NUMBER_FIELD = "(//input[contains(@type,'text')])[2]"
    EMAIL_BOX = "//input[contains(@placeholder,'Email')]"
    INSURANCE_ID_BOX = "//input[contains(@placeholder,'*ID')]"
    PHYSICIAN_DROPDOWN = "//input[@placeholder='*Physician']"
    Physician_Dropdown_Arrow = "//kendo-combobox[@placeholder='*Physician']//span[@class='k-button-icon k-icon k-i-caret-alt-down']"
    Insurance_Dropdown_Arrow = "//kendo-combobox[@placeholder='*Primary Insurance']//span[@class='k-button-icon k-icon k-i-caret-alt-down']"
    INSURANCE1_DROPDOWN = "(//span[@ng-reflect-ng-class='k-i-caret-alt-down'])[13]"
    SAVE_INITIATE_EPISODE_BUTTON = "//ion-text[contains(.,'Save & initiate Episode')]"
    Save_Patient_button = "//ion-text[contains(.,'save & close')]"
    Plus_Button_Office = "//div[@class='mb-5'][1]"
    Plus_Button_Fax = "//body/modal-container[1]/div[2]/div[1]/patient-registration[1]/div[1]/kendo-dialog[1]/div[2]/div[1]/div[1]/episodic-patient-registration[1]/div[1]/div[1]/ngx-simplebar[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[3]/div[2]/div[1]/div[3]/div[1]/div[2]/div[2]/ion-button[1]"
    Office_No_Option = "//ion-text[contains(.,'Office')]"
    Fax_Number_Option = "//ion-text[contains(.,'Fax')]"
    Office_Number_Box = "/html/body/modal-container/div[2]/div/patient-registration/div/kendo-dialog/div[2]/div/div/episodic-patient-registration/div/div/ngx-simplebar/div[1]/div[2]/div/div/div/div/form/div/div[3]/div[2]/div[1]/div[3]/div[1]/div[1]/kendo-formfield/div/kendo-maskedtextbox/input"
    Fax_No_Box = "/html/body/modal-container/div[2]/div/patient-registration/div/kendo-dialog/div[2]/div/div/episodic-patient-registration/div/div/ngx-simplebar/div[1]/div[2]/div/div/div/div/form/div/div[3]/div[2]/div[1]/div[4]/div/div[1]/kendo-formfield/div/kendo-maskedtextbox/input"
    Group_ID_Box = "//input[@placeholder=' Group ID']"
    Note_Box = "//textarea[@placeholder='Notes']"
    Exclude_Report_Box = "//input[@type='checkbox']"
    Pin_Icon = "(//ion-button[@fill='clear'])[5]"
