// package SanityTestcases;

// //Generated by Selenium IDE

// import org.openqa.selenium.By;
// import org.openqa.selenium.WebDriver;
// import org.openqa.selenium.firefox.FirefoxDriver;
// import org.openqa.selenium.chrome.ChromeDriver;
// import org.openqa.selenium.remote.RemoteWebDriver;
// import org.openqa.selenium.remote.DesiredCapabilities;
// import org.openqa.selenium.Dimension;
// import org.openqa.selenium.WebElement;
// import org.openqa.selenium.interactions.Actions;
// import org.openqa.selenium.support.ui.ExpectedConditions;
// import org.openqa.selenium.support.ui.WebDriverWait;
// import org.openqa.selenium.JavascriptExecutor;
// import org.openqa.selenium.Alert;
// import org.openqa.selenium.Keys;
// import java.util.*;
// import java.net.MalformedURLException;
// import java.net.URL;
// import java.time.Duration;

// import org.testng.annotations.AfterClass;
// import org.testng.annotations.Test;

// import base.BaseTest;

// import org.testng.annotations.AfterClass;
// import org.testng.annotations.Test;
// import org.openqa.selenium.By;
// import org.openqa.selenium.WebDriver;
// import org.openqa.selenium.WebElement;
// import org.openqa.selenium.support.ui.ExpectedConditions;
// import org.openqa.selenium.support.ui.FluentWait;
// import org.openqa.selenium.support.ui.WebDriverWait;
// import org.testng.Assert;
// import org.testng.annotations.AfterClass;
// import org.testng.annotations.AfterTest;
// import org.testng.annotations.BeforeClass;
// import org.testng.annotations.Test;


// @Test
// public class OrdersEncounters extends BaseTest {
// 	JavascriptExecutor js;


//     @Test
//     public void testOrdersEncounters() throws InterruptedException {
//         Thread.sleep(5000);
//         driver.findElement(By.xpath("//h5[text()='Orders/Encounters']")).click();
//         driver.findElement(By.id("idSbMnuEncounters")).click();
//         hoverOverElement(By.id("idSbMnuMyEncounters"));
//         hoverOverBody();
//         System.out.println("Done1");
//         driver.findElement(By.id("btnApplyFilter")).click();
//         driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(1) .fa-eye")).click();
//         driver.findElement(By.id("doc_242055193-001.pdf")).click();
//         hoverOverElement(By.id("doc_242055193-001.pdf"));
//         System.out.println("Done2");
//         hoverOverBody();
//         System.out.println("Done3");
//         driver.findElement(By.cssSelector(".ng-star-inserted > .close")).click();
//         System.out.println("Done4");
//         System.out.println("Done5");
//         driver.findElement(By.id("idSbMnuEncounters")).click();
//         hoverOverElement(By.id("idMnuEncounterTracking"));
//         hoverOverBody();
//         driver.findElement(By.id("idSbMnuMyEncounters")).click();
//         driver.findElement(By.id("btnApplyFilter")).click();
//         driver.findElement(By.id("idSbMnuPendingReview")).click();
//         driver.findElement(By.cssSelector(".border-left")).click();
//         driver.findElement(By.id("btnApplyFilter")).click();
//         hoverOverElement(By.id("btnApplyFilter"));
//         hoverOverBody();
//         driver.findElement(By.id("idSbMnuMyReview")).click();
//         driver.findElement(By.id("btnApplyFilter")).click();
//         driver.findElement(By.id("idSbMnuAssistance")).click();
//         driver.findElement(By.id("idSbMnuIncompleteSummary")).click();
//         driver.findElement(By.id("idSbMnuIncompleteEncounters")).click();
//         driver.findElement(By.id("btnApplyFilter")).click();
//         driver.findElement(By.id("idSbMnuCompletedEncounters")).click();
//         driver.findElement(By.id("btnApplyFilter")).click();
//         driver.findElement(By.id("idSbMnuPendingEncounters")).click();
//         driver.findElement(By.id("btnApplyFilter")).click();
//         hoverOverElement(By.id("btnApplyFilter"));
//         hoverOverBody();
//         driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(1) .fa-eye")).click();
//         driver.findElement(By.cssSelector(".ng-star-inserted > .close")).click();
//         driver.findElement(By.id("idSbMnuArchivedEncounters")).click();
//         driver.findElement(By.id("btnApplyFilter")).click();
//         hoverOverElement(By.id("btnApplyFilter"));
//         hoverOverBody();
//         driver.findElement(By.id("377e3bf1-dcb1-4278-a5e1-4f6f2afdb0df")).click();
//         driver.findElement(By.id("btnApplyFilter")).click();
//         driver.findElement(By.id("idSbMnuSearch")).click();
//         driver.findElement(By.id("btnApplyFilter")).click();
//         hoverOverElement(By.id("btnApplyFilter"));
//         hoverOverBody();
//         driver.findElement(By.cssSelector(".k-switch-label-off")).click();
//         driver.findElement(By.id("btnApplyFilter")).click();
//         hoverOverElement(By.id("btnApplyFilter"));
//         hoverOverBody();
//         driver.findElement(By.id("idSbMnuAdvanceSearch")).click();
//         driver.findElement(By.id("btnApplyFilter")).click();
//         driver.findElement(By.cssSelector(".k-switch-handle")).click();
//         driver.findElement(By.id("btnApplyFilter")).click();
//         hoverOverElement(By.id("btnApplyFilter"));
//         hoverOverBody();
//         driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(1) .fa-eye")).click();
//         driver.findElement(By.cssSelector(".ng-star-inserted > .close")).click();
//         driver.findElement(By.id("idSbMnuExport")).click();
//         hoverOverElement(By.linkText("Current Status"));
//         driver.findElement(By.id("btnApplyFilter")).click();
//         hoverOverElement(By.id("btnApplyFilter"));
//         hoverOverBody();
//         driver.findElement(By.id("idSbMnuReprocessFolder")).click();
//         driver.findElement(By.id("idMnuMissingInformation")).click();
//         driver.findElement(By.id("idSbMnuUserEncounters")).click();
//         hoverOverElement(By.id("idSbMnuUserEncounters"));
//         hoverOverBody();
//         driver.findElement(By.id("btnApplyFilter")).click();
//         hoverOverElement(By.id("btnApplyFilter"));
//         hoverOverBody();
//         driver.findElement(By.id("idSbMnuPracticeAssistanceCompleted")).click();
//         driver.findElement(By.id("btnApplyFilter")).click();
//         hoverOverElement(By.id("btnApplyFilter"));
//         hoverOverBody();
//         driver.findElement(By.id("idSbMnuPracticeAssigned")).click();
//         driver.findElement(By.id("btnApplyFilter")).click();
//         hoverOverElement(By.id("btnApplyFilter"));
//         hoverOverBody();
//         driver.findElement(By.id("idSbMnuPracticeCompleted")).click();
//         driver.findElement(By.id("btnApplyFilter")).click();
//         hoverOverElement(By.id("btnApplyFilter"));
//         hoverOverBody();
//     }

//     private void hoverOverElement(By by) {
//         WebElement element = driver.findElement(by);
//         Actions builder = new Actions(driver);
//         builder.moveToElement(element).perform();
//     }

//     private void hoverOverBody() {
//         WebElement element = driver.findElement(By.tagName("body"));
//         Actions builder = new Actions(driver);
//         builder.moveToElement(element, 0, 0).perform();
//     }


// @Test
// public void testOrdersEncounters1() throws InterruptedException {
//     // ... (existing steps)

//     driver.findElement(By.id("btnApplyFilter")).click();
//     Assert.assertTrue(driver.findElement(By.cssSelector(".filtered-results")).isDisplayed(), "Filtered results should be displayed");

//     // ... (remaining steps)
// }

// }
// //Generated by Selenium IDE
// import org.junit.Test;
// import org.junit.Before;
// import org.junit.After;
// import static org.junit.Assert.*;
// import static org.hamcrest.CoreMatchers.is;
// import static org.hamcrest.core.IsNot.not;
// import org.openqa.selenium.By;
// import org.openqa.selenium.WebDriver;
// import org.openqa.selenium.firefox.FirefoxDriver;
// import org.openqa.selenium.chrome.ChromeDriver;
// import org.openqa.selenium.remote.RemoteWebDriver;
// import org.openqa.selenium.remote.DesiredCapabilities;
// import org.openqa.selenium.Dimension;
// import org.openqa.selenium.WebElement;
// import org.openqa.selenium.interactions.Actions;
// import org.openqa.selenium.support.ui.ExpectedConditions;
// import org.openqa.selenium.support.ui.WebDriverWait;
// import org.openqa.selenium.JavascriptExecutor;
// import org.openqa.selenium.Alert;
// import org.openqa.selenium.Keys;
// import java.util.*;
// import java.net.MalformedURLException;
// import java.net.URL;
// public class OEEEETest {
// private WebDriver driver;
// private Map<String, Object> vars;
// JavascriptExecutor js;
// @Before
// public void setUp() {
//  driver = new ChromeDriver();
//  js = (JavascriptExecutor) driver;
//  vars = new HashMap<String, Object>();
// }
// @After
// public void tearDown() {
//  driver.quit();
// }
// @Test
// public void oEEEE() {
//  driver.get("https://qonductor-staging.myqone.com/");
//  driver.manage().window().setSize(new Dimension(1580, 840));
//  driver.findElement(By.cssSelector("#optEncounters .ml-3 > div")).click();
//  driver.findElement(By.id("idMnuDashboard")).click();
//  driver.findElement(By.id("idSbMnuEncounterStatus")).click();
//  driver.findElement(By.cssSelector("#k-tabstrip-tab-1 > .k-link")).click();
//  driver.findElement(By.cssSelector("#k-tabstrip-tab-2 > .k-link")).click();
//  driver.findElement(By.cssSelector(".k-button")).click();
//  driver.findElement(By.id("df3607ab-e32e-41ae-a7cd-7c1b62e83ac9")).click();
//  driver.findElement(By.cssSelector("#k-tabstrip-tab-3 > .k-link")).click();
//  driver.findElement(By.cssSelector("#k-tabstrip-tab-4 > .k-link")).click();
//  driver.findElement(By.cssSelector("#k-tabstrip-tab-5 > .k-link")).click();
//  driver.findElement(By.id("btnApplyFilter")).click();
//  {
//    WebElement element = driver.findElement(By.id("btnApplyFilter"));
//    Actions builder = new Actions(driver);
//    builder.moveToElement(element).perform();
//  }
//  {
//    WebElement element = driver.findElement(By.tagName("body"));
//    Actions builder = new Actions(driver);
//    builder.moveToElement(element, 0, 0).perform();
//  }
//  driver.findElement(By.cssSelector(".fa-refresh")).click();
//  driver.findElement(By.id("idSbMnuExecutiveDashboard")).click();
//  driver.findElement(By.id("btnApplyFilter")).click();
//  driver.findElement(By.id("idSbMnuPracticeDashboard")).click();
//  driver.findElement(By.cssSelector(".k-switch-label-off")).click();
//  driver.findElement(By.id("idSbMnuPracticeProviderExecutiveDashboard")).click();
//  driver.findElement(By.id("btnApplyFilter")).click();
//  driver.findElement(By.id("idMnuDocuments")).click();
//  driver.findElement(By.id("idSbMnuBiotechAddOns")).click();
//  driver.findElement(By.id("idSbMnuBiotechDocumentSearch")).click();
//  driver.findElement(By.id("btnApplyFilter")).click();
//  driver.findElement(By.id("idMnuPrinting")).click();
//  driver.findElement(By.id("idSbMnuReadyForPrinting")).click();
//  {
//    WebElement element = driver.findElement(By.id("btnApplyFilter"));
//    Actions builder = new Actions(driver);
//    builder.moveToElement(element).perform();
//  }
//  {
//    WebElement element = driver.findElement(By.tagName("body"));
//    Actions builder = new Actions(driver);
//    builder.moveToElement(element, 0, 0).perform();
//  }
//  driver.findElement(By.cssSelector(".k-i-loading")).click();
//  driver.findElement(By.id("btnApplyFilter")).click();
//  driver.findElement(By.id("idSbMnuSubmittedAndPrinted")).click();
//  driver.findElement(By.id("btnApplyFilter")).click();
//  driver.findElement(By.id("idSbMnuOrdersReprint")).click();
//  driver.findElement(By.cssSelector(".k-state-focused")).click();
//  driver.findElement(By.cssSelector(".k-state-focused")).click();
//  {
//    WebElement element = driver.findElement(By.cssSelector(".mt-2 > .k-primary"));
//    Actions builder = new Actions(driver);
//    builder.moveToElement(element).perform();
//  }
//  {
//    WebElement element = driver.findElement(By.tagName("body"));
//    Actions builder = new Actions(driver);
//    builder.moveToElement(element, 0, 0).perform();
//  }
// }
// }


