# QInsight API Performance Testing Framework Configuration
# Configuration for QInsight API Performance Testing

# Authentication Configuration for Dynamic Token Management
authentication:
  qa_environment:
    enabled: true
    signin_url: "https://qore-qa.myqone.com/auth/signin"
    username: "tejas.automation@triarqhealth.com"
    password: "P@ssword1"
    token_cache_duration_hours: 1
    description: "Dynamic authentication for QA environment - fetches fresh tokens automatically"
  
  dev_environment:
    enabled: false
    description: "Static token authentication for Dev environment"
  
  staging_environment:
    enabled: false
    description: "Static token authentication for Staging environment"
  
  production_environment:
    enabled: false
    description: "Static token authentication for Production environment - use with extreme caution"

# Common Headers Configuration (Centralized Project-wide Headers)
common_headers:
  # Basic headers without authentication
  basic_no_auth:
    Content-Type: "application/json"
    User-Agent: "QInsight-Performance-Testing-Framework/1.0"
    Accept: "application/json"
  
  # QInsight headers for QA environment (Dynamic Authentication Enabled)
  qinsight_qa:
    Content-Type: "application/json"
    User-Agent: "QInsight-Performance-Testing-Framework/1.0"
    Accept: "application/json"
    # Note: Authorization header will be dynamically populated by auth_service
    # Fallback static token (will be replaced by dynamic token when available)
    Authorization: "Bearer STATIC_FALLBACK_TOKEN_WILL_BE_REPLACED_BY_DYNAMIC_TOKEN"
  
  # QInsight headers for Dev environment
  qinsight_dev:
    Content-Type: "application/json"
    User-Agent: "QInsight-Performance-Testing-Framework/1.0"
    Accept: "application/json"
    Authorization: "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NTM3Nzc1ODMsImV4cCI6MTc1NjM2OTU4MywiaXNzIjoiY2xvdWQtZW5kcG9pbnRzLWRldkBxcGF0aHdheXMtZGV2LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwiYXVkIjoiaHR0cHM6Ly9xb3JlLWRldi5teXFvbmUuY29tIiwic3ViIjoiY2xvdWQtZW5kcG9pbnRzLWRldkBxcGF0aHdheXMtZGV2LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwiZW1haWwiOiJkZXYudGVzdEB0cmlhcnFoZWFsdGguY29tIiwidXNlcmlkIjoiZGV2LXVzZXItaWQtMTIzIiwiZmlyc3RuYW1lIjoiRGV2IiwibGFzdG5hbWUiOiJUZXN0ZXIifQ.DevTokenSignatureForDevelopmentEnvironmentTesting"
  
  # QInsight headers for Staging environment
  qinsight_staging:
    Content-Type: "application/json"
    User-Agent: "QInsight-Performance-Testing-Framework/1.0"
    Accept: "application/json"
    Authorization: "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NTM3Nzc1ODMsImV4cCI6MTc1NjM2OTU4MywiaXNzIjoiY2xvdWQtZW5kcG9pbnRzLXN0YWdpbmdAcXBhdGh3YXlzLXN0YWdpbmcuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJhdWQiOiJodHRwczovL3FvcmUtc3RhZ2luZy5teXFvbmUuY29tIiwic3ViIjoiY2xvdWQtZW5kcG9pbnRzLXN0YWdpbmdAcXBhdGh3YXlzLXN0YWdpbmcuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJlbWFpbCI6InN0YWdpbmcudGVzdEB0cmlhcnFoZWFsdGguY29tIiwidXNlcmlkIjoic3RhZ2luZy11c2VyLWlkLTQ1NiIsImZpcnN0bmFtZSI6IlN0YWdpbmciLCJsYXN0bmFtZSI6IlRlc3RlciJ9.StagingTokenSignatureForStagingEnvironmentTesting"
  
  # QInsight headers for Production environment
  qinsight_production:
    Content-Type: "application/json"
    User-Agent: "QInsight-Performance-Testing-Framework/1.0"
    Accept: "application/json"
    Authorization: "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NTM3Nzc1ODMsImV4cCI6MTc1NjM2OTU4MywiaXNzIjoiY2xvdWQtZW5kcG9pbnRzLXByb2RAcXBhdGh3YXlzLXByb2QuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJhdWQiOiJodHRwczovL3FvcmUubXlxb25lLmNvbSIsInN1YiI6ImNsb3VkLWVuZHBvaW50cy1wcm9kQHFwYXRod2F5cy1wcm9kLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwiZW1haWwiOiJwcm9kLnNlcnZpY2VAdHJpYXJxaGVhbHRoLmNvbSIsInVzZXJpZCI6InByb2QtdXNlci1pZC03ODkiLCJmaXJzdG5hbWUiOiJQcm9kIiwibGFzdG5hbWUiOiJTZXJ2aWNlIn0.ProductionTokenSignatureForProductionEnvironmentTesting"
  
  # Analytics headers with environment-specific auth (Dynamic Authentication Enabled)
  qinsight_analytics_qa:
    Content-Type: "application/json"
    User-Agent: "QInsight-Analytics-Framework/1.0"
    Accept: "application/json"
    X-API-Version: "v1"
    # Note: Authorization header will be dynamically populated by auth_service
    # Fallback static token (will be replaced by dynamic token when available)
    Authorization: "Bearer STATIC_FALLBACK_TOKEN_WILL_BE_REPLACED_BY_DYNAMIC_TOKEN"
  
  qinsight_analytics_dev:
    Content-Type: "application/json"
    User-Agent: "QInsight-Analytics-Framework/1.0"
    Accept: "application/json"
    X-API-Version: "v1"
    Authorization: "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NTM3Nzc1ODMsImV4cCI6MTc1NjM2OTU4MywiaXNzIjoiY2xvdWQtZW5kcG9pbnRzLWRldkBxcGF0aHdheXMtZGV2LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwiYXVkIjoiaHR0cHM6Ly9xb3JlLWRldi5teXFvbmUuY29tIiwic3ViIjoiY2xvdWQtZW5kcG9pbnRzLWRldkBxcGF0aHdheXMtZGV2LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwiZW1haWwiOiJkZXYudGVzdEB0cmlhcnFoZWFsdGguY29tIiwidXNlcmlkIjoiZGV2LXVzZXItaWQtMTIzIiwiZmlyc3RuYW1lIjoiRGV2IiwibGFzdG5hbWUiOiJUZXN0ZXIifQ.DevTokenSignatureForDevelopmentEnvironmentTesting"
  
  qinsight_analytics_staging:
    Content-Type: "application/json"
    User-Agent: "QInsight-Analytics-Framework/1.0"
    Accept: "application/json"
    X-API-Version: "v1"
    Authorization: "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NTM3Nzc1ODMsImV4cCI6MTc1NjM2OTU4MywiaXNzIjoiY2xvdWQtZW5kcG9pbnRzLXN0YWdpbmdAcXBhdGh3YXlzLXN0YWdpbmcuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJhdWQiOiJodHRwczovL3FvcmUtc3RhZ2luZy5teXFvbmUuY29tIiwic3ViIjoiY2xvdWQtZW5kcG9pbnRzLXN0YWdpbmdAcXBhdGh3YXlzLXN0YWdpbmcuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJlbWFpbCI6InN0YWdpbmcudGVzdEB0cmlhcnFoZWFsdGguY29tIiwidXNlcmlkIjoic3RhZ2luZy11c2VyLWlkLTQ1NiIsImZpcnN0bmFtZSI6IlN0YWdpbmciLCJsYXN0bmFtZSI6IlRlc3RlciJ9.StagingTokenSignatureForStagingEnvironmentTesting"
  
  qinsight_analytics_production:
    Content-Type: "application/json"
    User-Agent: "QInsight-Analytics-Framework/1.0"
    Accept: "application/json"
    X-API-Version: "v1"
    Authorization: "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NTM3Nzc1ODMsImV4cCI6MTc1NjM2OTU4MywiaXNzIjoiY2xvdWQtZW5kcG9pbnRzLXByb2RAcXBhdGh3YXlzLXByb2QuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJhdWQiOiJodHRwczovL3FvcmUubXlxb25lLmNvbSIsInN1YiI6ImNsb3VkLWVuZHBvaW50cy1wcm9kQHFwYXRod2F5cy1wcm9kLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwiZW1haWwiOiJwcm9kLnNlcnZpY2VAdHJpYXJxaGVhbHRoLmNvbSIsInVzZXJpZCI6InByb2QtdXNlci1pZC03ODkiLCJmaXJzdG5hbWUiOiJQcm9kIiwibGFzdG5hbWUiOiJTZXJ2aWNlIn0.ProductionTokenSignatureForProductionEnvironmentTesting"

# Environment Settings
environments:
  dev:
    base_url: "https://qinsight-dev.myqone.com"
    timeout: 45
    verify_ssl: true
    description: "QInsight Dev Environment for analytics and metrics testing"
  
  qa:
    base_url: "https://qinsight-qa.myqone.com"
    timeout: 45
    verify_ssl: true
    description: "QInsight QA Environment for analytics and metrics testing"
  
  staging:
    base_url: "https://qinsight-staging.myqone.com"
    timeout: 45
    verify_ssl: true
    description: "QInsight Staging Environment for pre-production testing"
  
  production:
    base_url: "https://qinsight.myqone.com"
    timeout: 45
    verify_ssl: true
    description: "QInsight Production Environment - use with caution"

# Load Configuration Templates (Reusable across endpoints)
load_configurations:
  light_load:
    users: 20
    spawn_rate: 5
    duration: "90s"
    description: "Light load testing - baseline performance validation"
    expected_rps: 1.0
    max_response_time: 4000
    max_error_rate: 0
  
  medium_load:
    users: 30
    spawn_rate: 5
    duration: "90s"
    description: "Medium load testing - moderate stress testing"
    expected_rps: 0.8
    max_response_time: 30000
    max_error_rate: 8.0
  
  heavy_load:
    users: 40
    spawn_rate: 8
    duration: "120s"
    description: "Heavy load testing - stress testing"
    expected_rps: 0.6
    max_response_time: 40000
    max_error_rate: 10.0
  
  extreme_stress:
    users: 50
    spawn_rate: 10
    duration: "180s"
    description: "Extreme stress testing - pushing system to limits"
    expected_rps: 0.5
    max_response_time: 50000
    max_error_rate: 15.0
  
  endurance_test:
    users: 25
    spawn_rate: 3
    duration: "600s"
    description: "Endurance testing - extended duration stability test"
    expected_rps: 0.7
    max_response_time: 35000
    max_error_rate: 8.0
  
  spike_test:
    users: 35
    spawn_rate: 10
    duration: "180s"
    description: "Spike testing - rapid load increase testing"
    expected_rps: 0.9
    max_response_time: 35000
    max_error_rate: 12.0

# API Configuration - Complete API definitions with method, endpoint, headers, and payload
api_configurations:
  charges_analysis:
    name: "QInsight Charges Analysis API"
    description: "API for analyzing charges by CPT codes and practice metrics"
    method: "POST"
    endpoint: "/restservicefmetrics/ChargesAnalysisByCPT"
    # Reference to common headers (will be environment-specific at runtime)
    headers_template: "qinsight_qa"
    # Override or add specific headers if needed
    custom_headers: {}
    timeout: 45
    retry_attempts: 3
    retry_delay: 2
    payload:
      {"clientkey":"QinsightQAData","practicelist":["GCPBQDEMO4","GCPBQDEMO1"]}

# Legacy API Endpoints Configuration (Backward Compatibility)
api_endpoints:
  charges_analysis:
    path: "/restservicefmetrics/ChargesAnalysisByCPT"
    name: "QInsight Charges Analysis API"
    description: "API for analyzing charges by CPT codes and practice metrics"

# Test Combinations (Load Config + Endpoint combinations)
load_tests:
  # QInsight Charges Analysis API tests
  light_load:
    load_config: "light_load"
    endpoint: "charges_analysis"
    description: "Light load testing - QInsight charges analysis API"
  
  medium_load:
    load_config: "medium_load"
    endpoint: "charges_analysis"
    description: "Medium load testing - QInsight charges analysis API"
  
  heavy_load:
    load_config: "heavy_load"
    endpoint: "charges_analysis"
    description: "Heavy load testing - QInsight charges analysis API"
  
  # Special test scenarios
  stress_test:
    load_config: "extreme_stress"
    endpoint: "charges_analysis"
    description: "Extreme stress testing - push QInsight charges analysis API to limits"
  
  endurance_test:
    load_config: "endurance_test"
    endpoint: "charges_analysis"
    description: "Endurance testing - extended duration stability test (QInsight API)"
  
  spike_test:
    load_config: "spike_test"
    endpoint: "charges_analysis"
    description: "Spike testing - rapid load increase testing (QInsight API)"

# Performance Thresholds and SLA Definitions
thresholds:
  response_time:
    excellent: 3000      # ms - Best case performance
    good: 8000          # ms - Acceptable performance
    acceptable: 15000   # ms - Warning threshold
    critical: 25000     # ms - Critical threshold
    timeout: 45000      # ms - Request timeout
  
  error_rate:
    excellent: 0.5      # % - Best case error rate
    good: 2.0          # % - Acceptable error rate
    acceptable: 5.0    # % - Warning threshold
    critical: 10.0     # % - Critical threshold
  
  throughput:
    minimum_rps: 0.3   # Minimum requests per second
    target_rps: 0.8    # Target requests per second
    optimal_rps: 1.5   # Optimal requests per second

# Test Data for Various Test Scenarios
test_data:
  # Client keys for different test scenarios
  client_keys:
    qa: "QinsightQAData"
    dev: "QinsightDevData"
    staging: "QinsightStagingData"
  
  # Practice lists for load testing variety
  practice_lists:
    small:
      - "GCPBQDEMO1"
    
    medium:
      - "GCPBQDEMO1"
      - "GCPBQDEMO4"
    
    large:
      - "GCPBQDEMO1"
      - "GCPBQDEMO4"
      - "GCPBQDEMO2"
      - "GCPBQDEMO3"
  
  # Alternative payloads for load testing
  test_payloads:
    default:
      clientkey: "QinsightQAData"
      practicelist:
        - "GCPBQDEMO4"
        - "GCPBQDEMO1"
    
    single_practice:
      clientkey: "QinsightQAData"
      practicelist:
        - "GCPBQDEMO1"
    
    large_practice_set:
      clientkey: "QinsightQAData"
      practicelist:
        - "GCPBQDEMO1"
        - "GCPBQDEMO4"
        - "GCPBQDEMO2"
        - "GCPBQDEMO3"

# Reporting Configuration
reporting:
  pdf_generation:
    enabled: true
    template_path: "reports/pdf_generator/"
    output_path: "reports/pdf_generator/"
  
  html_reports:
    enabled: true
    output_path: "reports/"
    
  metrics:
    collect_detailed: true
    response_time_percentiles: [50, 75, 90, 95, 99]
    error_tracking: true

# Framework Configuration
framework:
  log_level: "INFO"
  retry_failed_requests: true
  collect_metrics: true
  save_raw_results: false
  api_type: "qinsight" 